keep-render-alive:
  image: curlimages/curl:latest
  script:
    - echo "Pinging backend"
    - curl -s https://marketplace-backend-prqr.onrender.com/api/v1/categories
    - echo "Backend pinged successfully"
  only:
    - schedules
